build: fix build with Meson >= 0.61, for i18n.merge_file()
Ignored in Meson < 0.60.0, deprecated since 0.60.1 and fatal since
0.61.0.

The error was:
```
ERROR: Function does not take positional arguments.
```

Cherry-picked from an earlier commit, and take same commit message as in
gedit-plugins.

Fixes https://gitlab.gnome.org/GNOME/gedit/-/issues/531